[package]
name = "fvm"
version = "0.1.0"
edition = "2021"

build = "build.rs"

[dependencies]
clap = { version = "4.0.29", features = ["derive"] }
lalrpop-util = "0.19.8"
pretty = "0.11.3"
rustyline = "10.0.0"

[build-dependencies]
lalrpop = { version = "0.19.8", default-features = false }
